# Parameter List
source_cloud: "../data/cloud_bin_00_easy.pcd"
target_cloud: "../data/cloud_bin_01.pcd"
# source_cloud: "../data/frag_115.ply"
# target_cloud: "../data/frag_116.ply"
downsample: true
estimate_normal: true
voxel_resolution: 0.01
normal_est_radius: 0.05

icp_method: color    # pcl, classic, color
icp_max_corres_dist: 0.05
icp_transformation_epsilon: 0.000001
icp_max_iterations: 20

