# Parameter List
# source_cloud: "../data/cloud_bin_00_easy.pcd"
# target_cloud: "../data/cloud_bin_01.pcd"
source_cloud: "../data/frag_115.ply"
target_cloud: "../data/frag_116.ply"
downsample: true
estimate_normal: true
voxel_resolution: 0.01
normal_est_radius: 0.05
search_radius: 0.04

icp_method: color    # pcl, classic, color
icp_max_corres_dist: 0.05
icp_transformation_epsilon: 0.000001  # not being used yet
icp_max_iterations: 10
color_icp_lambda: 0.968  # default 0.968 as in the paper
color_visualization: true
